### ISSUE TITLE
Don't use column names/labels as CSS classes

### ISSUE THREAD

**Issue by 3noch** [level12/webgrid#11]
Nick and I spent almost an hour tracking this one down: One of my grid columns was coming from our `LookupMixin` which has a column named `label`. I was showing that label on webgrid and you could filter it. But webgrid used the column name `label` as the class on the filter HTML. Bootstrap _also_ has a `label` class. So you can imagine the styling was all wrong.

Basically this was an extremely surprising bug and we really should not be doing this. We should derive some highly unlikely name for our CSS classes instead of copying directly from the column names.

**Comment by guruofgentoo** [comment]
It appears this has long since been resolved.

**Comment by 3noch** [comment]
Glad to hear it.
