### ISSUE TITLE
Add openpyxl support to XLSX renderer

### ISSUE THREAD

**Issue by bchopson** [level12/webgrid#121]
Once blazelibs/blazeutils#18 is addressed, we'll need to update the XLSX renderer to support openpyxl, since WriterX will default to using openpyxl if installed. The XLSX renderer is currently specific to xlsxwriter

**Comment by pytrumpeter** [comment]
@guruofgentoo Do we still need to maintain support for xlsxwriter in webgrid, in addition to openpyxl?

**Comment by guruofgentoo** [comment]
I would, just because there are apps that extend the renderer using xlsxwriter.

**Comment by pytrumpeter** [comment]
@guruofgentoo I've been able to implement basic support for both libraries now. One thing that's still a big sticking point is the vast difference in how styles get applied between the two libraries.  Blazeutils has a `style` parameter which it then applies directly to the openpyxl cell(s), but `cell.style` only takes builtin styles, and there aren't that many.  Here's what the headers look like with the "Title" style applied:

![image](https://user-images.githubusercontent.com/2653622/211054946-5882f795-df57-4f41-998e-3e1529e99762.png)

I can certainly change blazeutils to accept the much more flexible openpyxl objects like `Font`, `Border`, `Alignment` etc. Do you think it's worth moving forward with that change?

**Comment by guruofgentoo** [comment]
I'd accept a PR in blazeutils for that, with the guideline that I'd want to preserve backwards compatibility if possible.
