### ISSUE TITLE
Improve UX for adding filter

### ISSUE THREAD

**Issue by rsyring** [level12/webgrid#125]
Right now, to add a filter to a grid, it requires four clicks:

1. Add Filter Select: click to open
1. Add Filter Select: click to select filter to add
1. New Column Filter: select operator
1. New Column Filter: click the value entry field that was just made visible

And only then can you start typing.  There are probably better ways to do this entire UX when we build 2.0, but until then, I think it would be a quick win to:

* Change the "Add Filter" select to a "Filter On" series of checkboxes:
   - Convert to a series of checkboxes at the top of the control box that correspond to each column where a filter would be available.  
   - Label would be the column name, checked box indicates I want to filter by the field (and shows the field filter below it just like it does now).  Unchecking the box removes the filter.
   - Use a pipe to separate, e.g. `Filter On: Site [] | Employee [] | Tech [] | Priority []`
* Select a default operator for every filter type.  E.g. I almost always use the `contains` operator for a text field and the `is` operator for an options filter.
* Focus the cursor in the first/only value box that shows up for the filter just added.

This will reduce the number of clicks to add a filter to a single click and then type the value.

Thought should be given to how we will handle saved grid info in a session that would now likely have a different structure.  I think it might be a good time to add a "schema_version" to the data-structure we save in the session.  Upon reading the session data, if that value is missing or lower than the current schema version of the webgrid library, discard the schema.  This will mean some users could lose their default filters from the session but I think that's an ok trade off to breaking or spending extra time trying to handle "old" schemas.

**Comment by guruofgentoo** [comment]
Summary of Slack discussion: due to the large number of filterable columns we generally have on our grids, we'll forego the checkboxes for now and keep the select. But, that will give us a two-click solution in place of the current four-click.

I believe the current session store will handle this without any problems, but we'll follow the same schema versioning idea if needed for other updates.
