### ISSUE TITLE
'DateFilter' cannot be used with 'ArrowType' columns

### ISSUE THREAD

**Issue by tjlevel12** [level12/webgrid#136]
Attempting to use a `DateFilter` with an `ArrowType` column results in the following error:

```
AttributeError: 'datetime.date' object has no attribute 'to'
  File "sqlalchemy/engine/base.py", line 1175, in _execute_context
    context = constructor(dialect, self, conn, *args)
  File "sqlalchemy/engine/default.py", line 827, in _init_compiled
    param = dict(
  File "sqlalchemy/engine/default.py", line 830, in <genexpr>
    processors[key](compiled_params[key])
  File "sqlalchemy/sql/type_api.py", line 1232, in process
    return process_param(value, dialect)
  File "sqlalchemy_utils/types/arrow.py", line 73, in process_bind_param
    utc_val = self._coerce(value).to('UTC')

StatementError: (builtins.AttributeError) 'datetime.date' object has no attribute 'to'
```

As a workaround until this is resolved, a `DateTimeFilter` works with no problems.

**Comment by bchopson** [comment]
I just ran into this again.

**Comment by guruofgentoo** [comment]
@tjlevel12 and @bchopson I'm probably missing something obvious here, but: what's the use case? Generally I'd think of arrow-type fields as timestamps, i.e. date and time, and needing to be filtered as such. I'm happy to take a look at fixing this if there's a good case for using the date-only filter with it, that just wasn't the intent.

**Comment by bchopson** [comment]
@guruofgentoo My use case are Stripe timestamp fields for a subscription due date in a json column. While they might be stored as a timestamp, to the user they are a date and it would be simpler for them to only see options to filter by date. I suppose casting such values to dates might work...

**Comment by guruofgentoo** [comment]
I see. It's strange to me that those would be timestamps instead of just dates, but I understand the case now. Casting may be the simplest solution here, and we can do that in the filter, I think, by detecting the arrow type and casting if necessary.

**Comment by guruofgentoo** [comment]
Resolved in master.
