### ISSUE TITLE
Webgrid saves new session for every page view and never cleans up old sessions

### ISSUE THREAD

**Issue by matthiaswh** [level12/webgrid#137]
This leads to the session cookie ballooning in size, eventually maxing out the browser's cookie size limit.

Annoyingly, there are no errors or indications when the cookie's max size is reached. Data simply and quietly ceases to be persisted, leading to all sorts of difficult to troubleshoot problems.

When the user logs out, the session cookie is not completely cleared. This means logging out and back in is not enough to fix the issue for the user, they must clear the session cookie manually.

**Comment by guruofgentoo** [comment]
Planned changes:
- no need to store empty sessions (i.e. only key in the dict is "datagrid", no filter/sort)
- compare vals to existing default session, if any
  - only persist a new session if different from the default
- store timestamp on each session, and have an option on the grid to set max session store time in hours
  - allow this to be None to turn the behavior off
  - add session-cleanup step to drop any sessions (excluding the default) that are older than the max

With the above approach:
- if another tab loads the grid, user will still get the "default" (i.e. latest) session values, but that data set will not be automatically copied for another session key
- if no filter/sort applied, the grid effectively stays with default session, and coming back to the page with the session key will load current default (which may be different from what the user had before, if multiple tabs/windows are running the same grid)
- applying a new set of filters will force the specific session into the cookie, and coming back to the page with the session key will load that in
