### ISSUE TITLE
'apply_search' is called for empty 'search_value' values

### ISSUE THREAD

**Issue by tjlevel12** [level12/webgrid#144]
Currently, the grid's `self.search_value` gets set to an empty string `""` if no explicit search string is set by the user:
https://github.com/level12/webgrid/blob/a4dd7c3ad4bfc234e865e9aa81d84f808d9cd96a/webgrid/__init__.py#L1604-L1609

Since `"" is not None`, `self.apply_search` gets called even when no search string is specified:
https://github.com/level12/webgrid/blob/a4dd7c3ad4bfc234e865e9aa81d84f808d9cd96a/webgrid/__init__.py#L1472-L1473

**Comment by guruofgentoo** [comment]
I've also noted that the search param is not removed during reset.
