### ISSUE TITLE
SQLAlchemy incompatibility in testing methods

### ISSUE THREAD

**Issue by bchopson** [level12/webgrid#149]
https://github.com/level12/webgrid/blob/0.3.7/webgrid/testing.py#L89

`testing.query_to_str` calls `statement.session.get_bind` with `statement._mapper_zero()`, which does not appear to be defined for sqlalchemy 1.4.20 (at least).

Calling `statement.session.get_bind` with no arguments works for sqlalchemy 1.4.20.

**Comment by guruofgentoo** [comment]
Resolved in the #116 branch, which is now in master.
