### ISSUE TITLE
Maybe hide "Export to Excel" link if xlwt isn't installed

### ISSUE THREAD

**Issue by rsyring** [level12/webgrid#19]
From HLLAPI and RaceBetter GridView:

```python
        if g.export_to == 'xls':
            raise ImmediateResponse(g.xls.as_response())
```

Can result in:
```
AttributeError: 'NoneType' object has no attribute 'as_response'
```
when `xlwt` isn't installed.  Would it be better if we simply hid the link for exporting to Excel if the xls renderer isn't available?

**Comment by guruofgentoo** [comment]
Newer renderer link setup does this already.
