### ISSUE TITLE
Make the plus button in a multi select large so a user can see it

### ISSUE THREAD

**Issue by nZac** [level12/webgrid#2]
<img width="120" alt="screen shot 2016-03-23 at 11 39 00 am" src="https://cloud.githubusercontent.com/assets/276212/13992896/ded7fab2-f0eb-11e5-8cfc-c499562be21e.png">

The button is tiny and doesn't provide a ton of visual indication about purpose

**Comment by 3noch** [comment]
I wonder if the plus button is necessary at all, if all filters that supported multiselects just defaulted to using a multiselect in the first place.
