### ISSUE TITLE
default_op incorrectly changes has_filters

### ISSUE THREAD

**Issue by nZac** [level12/webgrid#23]
If you specify a `default_op` when creating a `Filter` it will incorrectly adjust the `has_filters` property of a grid when initially loading the grid.

**Comment by guruofgentoo** [comment]
Problem was in Filter.is_active's assumption that the presence of an op was enough to call the filter active. If a default op is used, other necessary data may not be provided for the filter to apply.

https://github.com/level12/webgrid/commit/0a5e60bf856349abda7ada6c0a4164c0b045db15 resolves this. If the default op doesn't take values (i.e. would apply anyway, like the Empty op, or DateFilter's This Month) then it will register as active. But if the default op needs a value(s) to operate, it won't be active unless it has at least one value provided.
