### ISSUE TITLE
Prefer to use string labels over column expressions when applying order_by

### ISSUE THREAD

**Issue by bladams** [level12/webgrid#25]
SQLAlchemy in version 1.1.5 no longer uses expression labels when generating the `ORDER BY` clause. I believe this has happened before and was eventually fixed but it seems like a recurring regression. 

For more consistent query generation, I think it would be a good idea to check for the presence of a string label on the column's expression and use that as the preferred argument to `order_by` [here](https://github.com/level12/webgrid/blob/master/webgrid/__init__.py#L238) and then falling back to the expression if no label is provided.

**Comment by guruofgentoo** [comment]
Since this has been out there for two years plus and not a big problem, closing.
