### ISSUE TITLE
give better context in exceptions during filter setup

### ISSUE THREAD

**Issue by guruofgentoo** [level12/webgrid#26]
OptionsFilterBase can give an exception `ValueError: value_modifier argument set to "auto", but the options set is empty and the type can therefore not be determined`. But there is no easy way to determine which filter on a grid is causing the issue. The exception should include the name of the filter.

**Comment by rsyring** [comment]
It's not obvious from the stack trace?

The error message could be improved, I'm just curious.

**Comment by guruofgentoo** [comment]
No, the stack trace shows only the line in OptionsFilterBase and the loop in BaseGrid which calls the filter. Anything related to a subclass doesn't make it into the trace.
