### ISSUE TITLE
apply_qs_args() ends up with dict instead of MultiDict

### ISSUE THREAD

**Issue by rsyring** [level12/webgrid#35]
```
  File "agariadm/views/private.py", line 54, in make_grid
    g.apply_qs_args()
  File "webgrid/__init__.py", line 792, in apply_qs_args
    v1 = args.getlist(filter_v1_qsk)
  AttributeError: 'dict' object has no attribute 'getlist'
```
I can't say I really understand all this code anymore, but the only thing that makes sense in this code:

https://github.com/level12/webgrid/blob/de9903a81b8c7e6f75be4619a156bae472d21619/webgrid/__init__.py#L755

is that the result of `self.get_session_store()` can be a normal dictionary under some circumstance.  Code later on is assuming a `MultiDict`, hence the exception when `getlist()` is called.

**Comment by rsyring** [comment]
This manifests itself as an exception for grid URLs that otherwise past tests:

```
`/__init__.py", line 792, in apply_qs_args\n    v1 = args.getlist(filter_v1_qsk)\nAttributeError: \'dict\' object has no attribute \'getlist\'',)`
```

**Comment by rsyring** [comment]
@guruofgentoo per our Slack discussion, I believe you need to add backwards compatibility for this?

**Comment by guruofgentoo** [comment]
It's already in master. I need to cut the release.
