### ISSUE TITLE
HTML characters are not escaped in multi-select filter

### ISSUE THREAD

**Issue by tjlevel12** [level12/webgrid#51]
If a TextFilter is switched to a multi-select (via the multi-select toggle), values containing HTML characters are not escaped properly.

In the issue I ran into, one of my column values was `'<Unassigned>'`, which resulted in the following rendered HTML:

```
<li>
    <label>
        <input type="checkbox" name="selectItemv1(class_name)" value="7">
        <unassigned></unassigned>
    </label>
</li>
```

**Comment by guruofgentoo** [comment]
This was resolved when we moved away from having a toggle for multiselect.
