### ISSUE TITLE
Kick off only one Appveyor job for PRs

### ISSUE THREAD

**Issue by rsyring** [level12/webgrid#56]
by setting this in the appveyor.yml:

```yaml
# If a branch has a PR, don't build it separately.  Avoids queueing two appveyor runs for the same
# commit.
skip_branch_with_pr: true
```

**Comment by guruofgentoo** [comment]
Bears mentioning, a run will still start when a PR is created. This setting will just make sure the additional PR run won't get spawned when more commits are pushed to the branch.

See https://help.appveyor.com/discussions/questions/18437-skip_branch_with_pr-setting-doesnt-work

AppVeyor FTW.
